# fly.toml app configuration file generated for comp7940-lab5-jeff-cool-brook-9873 on 2025-03-02T12:14:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comp7940-lab5-jeff-cool-brook-9873'
primary_region = 'otp'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
